// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Data.proto

package com.nsk.cms.ptotobuf.proto;

public final class AcquisitionDataProto {
  private AcquisitionDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AcquisitionDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AcquisitionData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string time = 1;</code>
     */
    java.lang.String getTime();
    /**
     * <code>string time = 1;</code>
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    /**
     * <code>map&lt;int32, .MapValue&gt; dataMap = 2;</code>
     */
    int getDataMapCount();
    /**
     * <code>map&lt;int32, .MapValue&gt; dataMap = 2;</code>
     */
    boolean containsDataMap(
        int key);
    /**
     * Use {@link #getDataMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue>
    getDataMap();
    /**
     * <code>map&lt;int32, .MapValue&gt; dataMap = 2;</code>
     */
    java.util.Map<java.lang.Integer, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue>
    getDataMapMap();
    /**
     * <code>map&lt;int32, .MapValue&gt; dataMap = 2;</code>
     */

    com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue getDataMapOrDefault(
        int key,
        com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue defaultValue);
    /**
     * <code>map&lt;int32, .MapValue&gt; dataMap = 2;</code>
     */

    com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue getDataMapOrThrow(
        int key);
  }
  /**
   * Protobuf type {@code AcquisitionData}
   */
  public  static final class AcquisitionData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AcquisitionData)
      AcquisitionDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AcquisitionData.newBuilder() to construct.
    private AcquisitionData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AcquisitionData() {
      time_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AcquisitionData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              time_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                dataMap_ = com.google.protobuf.MapField.newMapField(
                    DataMapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue>
              dataMap__ = input.readMessage(
                  DataMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              dataMap_.getMutableMap().put(
                  dataMap__.getKey(), dataMap__.getValue());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.internal_static_AcquisitionData_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetDataMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.internal_static_AcquisitionData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData.class, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData.Builder.class);
    }

    private int bitField0_;
    public static final int TIME_FIELD_NUMBER = 1;
    private volatile java.lang.Object time_;
    /**
     * <code>string time = 1;</code>
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        time_ = s;
        return s;
      }
    }
    /**
     * <code>string time = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATAMAP_FIELD_NUMBER = 2;
    private static final class DataMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue>newDefaultInstance(
                  com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.internal_static_AcquisitionData_DataMapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue> dataMap_;
    private com.google.protobuf.MapField<java.lang.Integer, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue>
    internalGetDataMap() {
      if (dataMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            DataMapDefaultEntryHolder.defaultEntry);
      }
      return dataMap_;
    }

    public int getDataMapCount() {
      return internalGetDataMap().getMap().size();
    }
    /**
     * <code>map&lt;int32, .MapValue&gt; dataMap = 2;</code>
     */

    public boolean containsDataMap(
        int key) {
      
      return internalGetDataMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getDataMapMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue> getDataMap() {
      return getDataMapMap();
    }
    /**
     * <code>map&lt;int32, .MapValue&gt; dataMap = 2;</code>
     */

    public java.util.Map<java.lang.Integer, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue> getDataMapMap() {
      return internalGetDataMap().getMap();
    }
    /**
     * <code>map&lt;int32, .MapValue&gt; dataMap = 2;</code>
     */

    public com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue getDataMapOrDefault(
        int key,
        com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue defaultValue) {
      
      java.util.Map<java.lang.Integer, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue> map =
          internalGetDataMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, .MapValue&gt; dataMap = 2;</code>
     */

    public com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue getDataMapOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue> map =
          internalGetDataMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, time_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetDataMap(),
          DataMapDefaultEntryHolder.defaultEntry,
          2);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, time_);
      }
      for (java.util.Map.Entry<java.lang.Integer, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue> entry
           : internalGetDataMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue>
        dataMap__ = DataMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, dataMap__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData)) {
        return super.equals(obj);
      }
      com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData other = (com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData) obj;

      boolean result = true;
      result = result && getTime()
          .equals(other.getTime());
      result = result && internalGetDataMap().equals(
          other.internalGetDataMap());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
      if (!internalGetDataMap().getMap().isEmpty()) {
        hash = (37 * hash) + DATAMAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetDataMap().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AcquisitionData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AcquisitionData)
        com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.internal_static_AcquisitionData_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetDataMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableDataMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.internal_static_AcquisitionData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData.class, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData.Builder.class);
      }

      // Construct using com.nsk.WebServer.protobuf.proto.AcquisitionDataProto.AcquisitionData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        time_ = "";

        internalGetMutableDataMap().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.internal_static_AcquisitionData_descriptor;
      }

      @java.lang.Override
      public com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData getDefaultInstanceForType() {
        return com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData.getDefaultInstance();
      }

      @java.lang.Override
      public com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData build() {
        com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData buildPartial() {
        com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData result = new com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.time_ = time_;
        result.dataMap_ = internalGetDataMap();
        result.dataMap_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData) {
          return mergeFrom((com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData other) {
        if (other == com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData.getDefaultInstance()) return this;
        if (!other.getTime().isEmpty()) {
          time_ = other.time_;
          onChanged();
        }
        internalGetMutableDataMap().mergeFrom(
            other.internalGetDataMap());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object time_ = "";
      /**
       * <code>string time = 1;</code>
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string time = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string time = 1;</code>
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string time = 1;</code>
       */
      public Builder clearTime() {
        
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>string time = 1;</code>
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        time_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue> dataMap_;
      private com.google.protobuf.MapField<java.lang.Integer, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue>
      internalGetDataMap() {
        if (dataMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              DataMapDefaultEntryHolder.defaultEntry);
        }
        return dataMap_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue>
      internalGetMutableDataMap() {
        onChanged();;
        if (dataMap_ == null) {
          dataMap_ = com.google.protobuf.MapField.newMapField(
              DataMapDefaultEntryHolder.defaultEntry);
        }
        if (!dataMap_.isMutable()) {
          dataMap_ = dataMap_.copy();
        }
        return dataMap_;
      }

      public int getDataMapCount() {
        return internalGetDataMap().getMap().size();
      }
      /**
       * <code>map&lt;int32, .MapValue&gt; dataMap = 2;</code>
       */

      public boolean containsDataMap(
          int key) {
        
        return internalGetDataMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getDataMapMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue> getDataMap() {
        return getDataMapMap();
      }
      /**
       * <code>map&lt;int32, .MapValue&gt; dataMap = 2;</code>
       */

      public java.util.Map<java.lang.Integer, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue> getDataMapMap() {
        return internalGetDataMap().getMap();
      }
      /**
       * <code>map&lt;int32, .MapValue&gt; dataMap = 2;</code>
       */

      public com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue getDataMapOrDefault(
          int key,
          com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue defaultValue) {
        
        java.util.Map<java.lang.Integer, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue> map =
            internalGetDataMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, .MapValue&gt; dataMap = 2;</code>
       */

      public com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue getDataMapOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue> map =
            internalGetDataMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearDataMap() {
        internalGetMutableDataMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int32, .MapValue&gt; dataMap = 2;</code>
       */

      public Builder removeDataMap(
          int key) {
        
        internalGetMutableDataMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue>
      getMutableDataMap() {
        return internalGetMutableDataMap().getMutableMap();
      }
      /**
       * <code>map&lt;int32, .MapValue&gt; dataMap = 2;</code>
       */
      public Builder putDataMap(
          int key,
          com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue value) {
        
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableDataMap().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int32, .MapValue&gt; dataMap = 2;</code>
       */

      public Builder putAllDataMap(
          java.util.Map<java.lang.Integer, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue> values) {
        internalGetMutableDataMap().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AcquisitionData)
    }

    // @@protoc_insertion_point(class_scope:AcquisitionData)
    private static final com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData();
    }

    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AcquisitionData>
        PARSER = new com.google.protobuf.AbstractParser<AcquisitionData>() {
      @java.lang.Override
      public AcquisitionData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AcquisitionData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AcquisitionData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AcquisitionData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.AcquisitionData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MapValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MapValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double mapValue = 1;</code>
     */
    double getMapValue();
  }
  /**
   * Protobuf type {@code MapValue}
   */
  public  static final class MapValue extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MapValue)
      MapValueOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MapValue.newBuilder() to construct.
    private MapValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MapValue() {
      mapValue_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MapValue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              mapValue_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.internal_static_MapValue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.internal_static_MapValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue.class, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue.Builder.class);
    }

    public static final int MAPVALUE_FIELD_NUMBER = 1;
    private double mapValue_;
    /**
     * <code>double mapValue = 1;</code>
     */
    public double getMapValue() {
      return mapValue_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mapValue_ != 0D) {
        output.writeDouble(1, mapValue_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (mapValue_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, mapValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue)) {
        return super.equals(obj);
      }
      com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue other = (com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue) obj;

      boolean result = true;
      result = result && (
          java.lang.Double.doubleToLongBits(getMapValue())
          == java.lang.Double.doubleToLongBits(
              other.getMapValue()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MAPVALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMapValue()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MapValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MapValue)
        com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.internal_static_MapValue_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.internal_static_MapValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue.class, com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue.Builder.class);
      }

      // Construct using com.nsk.WebServer.protobuf.proto.AcquisitionDataProto.MapValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        mapValue_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.internal_static_MapValue_descriptor;
      }

      @java.lang.Override
      public com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue getDefaultInstanceForType() {
        return com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue.getDefaultInstance();
      }

      @java.lang.Override
      public com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue build() {
        com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue buildPartial() {
        com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue result = new com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue(this);
        result.mapValue_ = mapValue_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue) {
          return mergeFrom((com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue other) {
        if (other == com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue.getDefaultInstance()) return this;
        if (other.getMapValue() != 0D) {
          setMapValue(other.getMapValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double mapValue_ ;
      /**
       * <code>double mapValue = 1;</code>
       */
      public double getMapValue() {
        return mapValue_;
      }
      /**
       * <code>double mapValue = 1;</code>
       */
      public Builder setMapValue(double value) {
        
        mapValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double mapValue = 1;</code>
       */
      public Builder clearMapValue() {
        
        mapValue_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MapValue)
    }

    // @@protoc_insertion_point(class_scope:MapValue)
    private static final com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue();
    }

    public static com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MapValue>
        PARSER = new com.google.protobuf.AbstractParser<MapValue>() {
      @java.lang.Override
      public MapValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MapValue(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MapValue> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MapValue> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nsk.cms.ptotobuf.proto.AcquisitionDataProto.MapValue getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AcquisitionData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AcquisitionData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AcquisitionData_DataMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AcquisitionData_DataMapEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MapValue_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MapValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nData.proto\"\212\001\n\017AcquisitionData\022\014\n\004time" +
      "\030\001 \001(\t\022.\n\007dataMap\030\002 \003(\0132\035.AcquisitionDat" +
      "a.DataMapEntry\0329\n\014DataMapEntry\022\013\n\003key\030\001 " +
      "\001(\005\022\030\n\005value\030\002 \001(\0132\t.MapValue:\0028\001\"\034\n\010Map" +
      "Value\022\020\n\010mapValue\030\001 \001(\001B8\n com.nsk.WebSe" +
      "rver.protobuf.protoB\024AcquisitionDataProt" +
      "ob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AcquisitionData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AcquisitionData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AcquisitionData_descriptor,
        new java.lang.String[] { "Time", "DataMap", });
    internal_static_AcquisitionData_DataMapEntry_descriptor =
      internal_static_AcquisitionData_descriptor.getNestedTypes().get(0);
    internal_static_AcquisitionData_DataMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AcquisitionData_DataMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_MapValue_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MapValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MapValue_descriptor,
        new java.lang.String[] { "MapValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
