// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BuildExperiment.proto

package com.nsk.cms.ptotobuf.proto;

public final class ExperimentProto {
  private ExperimentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code proto.State}
   */
  public enum State
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CONFIG = 0;</code>
     */
    CONFIG(0),
    /**
     * <code>START = 1;</code>
     */
    START(1),
    /**
     * <code>END = 2;</code>
     */
    END(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CONFIG = 0;</code>
     */
    public static final int CONFIG_VALUE = 0;
    /**
     * <code>START = 1;</code>
     */
    public static final int START_VALUE = 1;
    /**
     * <code>END = 2;</code>
     */
    public static final int END_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static State valueOf(int value) {
      return forNumber(value);
    }

    public static State forNumber(int value) {
      switch (value) {
        case 0: return CONFIG;
        case 1: return START;
        case 2: return END;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<State>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        State> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<State>() {
            public State findValueByNumber(int number) {
              return State.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.nsk.cms.ptotobuf.proto.ExperimentProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final State[] VALUES = values();

    public static State valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private State(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.State)
  }

  public interface ExperimentMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ExperimentMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * =1 表示Tag Number 用于序列化，类似UUID
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <pre>
     * </pre>
     *
     * <code>.proto.State state = 2;</code>
     */
    int getStateValue();
    /**
     * <pre>
     * </pre>
     *
     * <code>.proto.State state = 2;</code>
     */
    com.nsk.cms.ptotobuf.proto.ExperimentProto.State getState();
  }
  /**
   * Protobuf type {@code proto.ExperimentMessage}
   */
  public  static final class ExperimentMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ExperimentMessage)
      ExperimentMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExperimentMessage.newBuilder() to construct.
    private ExperimentMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExperimentMessage() {
      id_ = 0;
      state_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExperimentMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              state_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nsk.cms.ptotobuf.proto.ExperimentProto.internal_static_proto_ExperimentMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nsk.cms.ptotobuf.proto.ExperimentProto.internal_static_proto_ExperimentMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage.class, com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     * =1 表示Tag Number 用于序列化，类似UUID
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int STATE_FIELD_NUMBER = 2;
    private int state_;
    /**
     * <pre>
     * </pre>
     *
     * <code>.proto.State state = 2;</code>
     */
    public int getStateValue() {
      return state_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.proto.State state = 2;</code>
     */
    public com.nsk.cms.ptotobuf.proto.ExperimentProto.State getState() {
      @SuppressWarnings("deprecation")
      com.nsk.cms.ptotobuf.proto.ExperimentProto.State result = com.nsk.cms.ptotobuf.proto.ExperimentProto.State.valueOf(state_);
      return result == null ? com.nsk.cms.ptotobuf.proto.ExperimentProto.State.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (state_ != com.nsk.cms.ptotobuf.proto.ExperimentProto.State.CONFIG.getNumber()) {
        output.writeEnum(2, state_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (state_ != com.nsk.cms.ptotobuf.proto.ExperimentProto.State.CONFIG.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, state_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage)) {
        return super.equals(obj);
      }
      com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage other = (com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && state_ == other.state_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ExperimentMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ExperimentMessage)
        com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nsk.cms.ptotobuf.proto.ExperimentProto.internal_static_proto_ExperimentMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nsk.cms.ptotobuf.proto.ExperimentProto.internal_static_proto_ExperimentMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage.class, com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage.Builder.class);
      }

      // Construct using com.nsk.Client.protobuf.proto.ExperimentProto.ExperimentMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        state_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nsk.cms.ptotobuf.proto.ExperimentProto.internal_static_proto_ExperimentMessage_descriptor;
      }

      @java.lang.Override
      public com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage getDefaultInstanceForType() {
        return com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage build() {
        com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage buildPartial() {
        com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage result = new com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage(this);
        result.id_ = id_;
        result.state_ = state_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage) {
          return mergeFrom((com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage other) {
        if (other == com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.state_ != 0) {
          setStateValue(other.getStateValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <pre>
       * =1 表示Tag Number 用于序列化，类似UUID
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       * =1 表示Tag Number 用于序列化，类似UUID
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * =1 表示Tag Number 用于序列化，类似UUID
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int state_ = 0;
      /**
       * <pre>
       * </pre>
       *
       * <code>.proto.State state = 2;</code>
       */
      public int getStateValue() {
        return state_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>.proto.State state = 2;</code>
       */
      public Builder setStateValue(int value) {
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>.proto.State state = 2;</code>
       */
      public com.nsk.cms.ptotobuf.proto.ExperimentProto.State getState() {
        @SuppressWarnings("deprecation")
        com.nsk.cms.ptotobuf.proto.ExperimentProto.State result = com.nsk.cms.ptotobuf.proto.ExperimentProto.State.valueOf(state_);
        return result == null ? com.nsk.cms.ptotobuf.proto.ExperimentProto.State.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>.proto.State state = 2;</code>
       */
      public Builder setState(com.nsk.cms.ptotobuf.proto.ExperimentProto.State value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>.proto.State state = 2;</code>
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.ExperimentMessage)
    }

    // @@protoc_insertion_point(class_scope:proto.ExperimentMessage)
    private static final com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage();
    }

    public static com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExperimentMessage>
        PARSER = new com.google.protobuf.AbstractParser<ExperimentMessage>() {
      @java.lang.Override
      public ExperimentMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExperimentMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExperimentMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExperimentMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nsk.cms.ptotobuf.proto.ExperimentProto.ExperimentMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ExperimentMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ExperimentMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025BuildExperiment.proto\022\005proto\"<\n\021Experi" +
      "mentMessage\022\n\n\002id\030\001 \001(\005\022\033\n\005state\030\002 \001(\0162\014" +
      ".proto.State*\'\n\005State\022\n\n\006CONFIG\020\000\022\t\n\005STA" +
      "RT\020\001\022\007\n\003END\020\002B0\n\035com.nsk.Client.protobuf" +
      ".protoB\017ExperimentProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_ExperimentMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ExperimentMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ExperimentMessage_descriptor,
        new java.lang.String[] { "Id", "State", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
